Import("env")
Import("install")

cursor_env = env.Clone()

cursor_env.Append(DPATH = ["source", "../client/source", "../common"])
cursor_env.Append(DFLAGS = "-fversion=WlStatic")

Import("util")
cursor_env.Append(LIBS = util)

cursor_env.Depends("source/wayland/cursor.o", "../client/source/wayland/client/protocol.d")

cursor = cursor_env.SharedLibrary(
	target = "wayland-cursor",
	source = [
	Glob("source/wayland/native/*.d"),
	Glob("source/wayland/*.d")
	]
)

env.Alias("cursor", cursor)

install_lib = cursor_env.InstallAs(
	target = "$PREFIX/lib/libwayland-d-cursor.so",
	source = cursor
)
install_include = cursor_env.Install(
	target = "$PREFIX/include/d/wayland/cursor",
	source = Glob("source/wayland/*.d")
)
cursor_install = [install_lib,  install_include]
env.Alias("install_cursor", cursor_install)
install.append(cursor_install)
